/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Enhanced health check endpoint.
         *     Returns the status of the daemon, providers, and vector store.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get database statistics.
         *     Returns counts of files, sections, tags, links, and last indexed time.
         */
        get: operations["get_stats_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Get available configuration options.
         *     Returns available providers, models, and RAG techniques.
         */
        get: operations["get_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search across the vault.
         *     Uses FTS5 for keyword matching with BM25 ranking.
         *     Returns snippets with highlighted matches.
         */
        get: operations["search_search_get"];
        put?: never;
        /**
         * Semantic Search
         * @description Semantic search across the vault (without LLM generation).
         *
         *     Uses embeddings for semantic similarity matching.
         *     Supports different RAG techniques for retrieval.
         */
        post: operations["semantic_search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Get full content of a specific file.
         *     Path should be relative to the vault root.
         */
        get: operations["get_file_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description List all tags in the vault.
         *     Useful for exploring the knowledge graph.
         */
        get: operations["list_tags_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backlinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backlinks
         * @description Find all files that link to a specific file.
         *     Useful for exploring connections in the knowledge graph.
         */
        get: operations["get_backlinks_backlinks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Reindex
         * @description Manually trigger a reindex of the vault.
         *     Use full=true to force a complete rescan.
         */
        post: operations["trigger_reindex_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Index
         * @description Trigger document indexing for the knowledge base.
         *
         *     Runs indexing in the background and returns a job ID for tracking.
         */
        post: operations["trigger_index_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Index Status
         * @description Get the current indexing status.
         */
        get: operations["get_index_status_index_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Question
         * @description Ask a question using RAG (Retrieval-Augmented Generation).
         *
         *     Searches the knowledge base for relevant content and uses an LLM
         *     to generate an answer based on the retrieved context.
         *
         *     Supports multiple providers, models, and RAG techniques.
         */
        post: operations["ask_question_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Embedding Stats
         * @description Get embedding statistics.
         *     Shows how many chunks have been embedded.
         */
        get: operations["get_embedding_stats_embeddings_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Inbox
         * @description Process documents in the inbox folder.
         *
         *     Classifies, tags, and moves documents from 00_Inbox to appropriate folders.
         *     Use dry_run=True to preview changes without moving files.
         */
        post: operations["process_inbox_inbox_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Inbox Files
         * @description List files currently in the inbox.
         *
         *     Returns files that would be processed on next inbox run.
         */
        get: operations["list_inbox_files_inbox_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inbox Contents
         * @description Get the full contents of the inbox folder including all subfolders.
         *
         *     Returns a hierarchical view of all files and folders in 00_Inbox.
         */
        get: operations["get_inbox_contents_inbox_contents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync To Postgres
         * @description Synchronize SQLite data to PostgreSQL.
         *
         *     This enables a Next.js frontend to access the Second Brain data via Prisma.
         *
         *     Modes:
         *     - incremental: Only sync files changed since last sync (faster)
         *     - full: Clear and rebuild all PostgreSQL data (slower but ensures consistency)
         */
        post: operations["sync_to_postgres_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Postgres Stats
         * @description Get PostgreSQL database statistics.
         *
         *     Returns counts and last sync time for the PostgreSQL database.
         */
        get: operations["postgres_stats_sync_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Single File
         * @description Sync a single file to PostgreSQL.
         *
         *     Use this for on-demand syncing when a file is updated.
         */
        post: operations["sync_single_file_sync_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List recent conversations.
         *
         *     Optionally filter by session_id for user-specific conversations.
         */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Create a new conversation.
         *
         *     Used by Next.js frontend to track chat sessions.
         */
        post: operations["create_conversation_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a conversation with all messages.
         */
        get: operations["get_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Message
         * @description Add a message to a conversation.
         */
        post: operations["add_message_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/embeddings/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Embeddings
         * @description Generate embeddings for pending chunks.
         *
         *     Processes chunks that don't have embeddings yet.
         *     Run this after indexing to enable RAG functionality.
         */
        post: operations["generate_embeddings_embeddings_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskRequest
         * @description Request body for /ask endpoint (new API spec).
         */
        AskRequest: {
            /** Question */
            question: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Provider
             * @default gemini
             */
            provider: string;
            /** Model */
            model?: string | null;
            /**
             * Rag Technique
             * @default basic
             */
            rag_technique: string;
            /**
             * Include Sources
             * @default true
             */
            include_sources: boolean;
        };
        /**
         * AskResponse
         * @description Response from RAG-powered Q&A.
         */
        AskResponse: {
            /** Answer */
            answer: string;
            /** Sources */
            sources: components["schemas"]["SourceInfo"][];
            /** Query */
            query: string;
        };
        /**
         * ConfigDefaults
         * @description Default configuration values.
         */
        ConfigDefaults: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Rag Technique */
            rag_technique: string;
        };
        /**
         * ConfigResponse
         * @description Response for /config endpoint.
         */
        ConfigResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderInfo"][];
            /** Rag Techniques */
            rag_techniques: components["schemas"]["RAGTechniqueInfo"][];
            defaults: components["schemas"]["ConfigDefaults"];
            /** Embedding Model */
            embedding_model: string;
            /**
             * Vector Store
             * @default sqlite
             */
            vector_store: string;
        };
        /**
         * ConversationCreate
         * @description Request to create a conversation.
         */
        ConversationCreate: {
            /** Session Id */
            session_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * EmbeddingStatsResponse
         * @description Embedding statistics response.
         */
        EmbeddingStatsResponse: {
            /** Chunk Count */
            chunk_count: number;
            /** Embedding Count */
            embedding_count: number;
            /** Files With Embeddings */
            files_with_embeddings: number;
            /** Pending Chunks */
            pending_chunks: number;
        };
        /**
         * FileResponse
         * @description File content response.
         */
        FileResponse: {
            /** Path */
            path: string;
            /** Title */
            title: string;
            /** Content */
            content: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Enhanced health check response.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
            /** Vault Path */
            vault_path: string;
            /** Watcher Running */
            watcher_running: boolean;
            /**
             * Providers
             * @default {}
             */
            providers: {
                [key: string]: components["schemas"]["ProviderStatus"];
            };
            vector_store?: components["schemas"]["VectorStoreStatus"] | null;
        };
        /**
         * InboxContentsResponse
         * @description Full contents of the inbox folder.
         */
        InboxContentsResponse: {
            /** Inbox Path */
            inbox_path: string;
            /** Total Files */
            total_files: number;
            /** Total Folders */
            total_folders: number;
            /** Root Files */
            root_files: components["schemas"]["InboxFileInfo"][];
            /** Folders */
            folders: components["schemas"]["InboxFolderInfo"][];
        };
        /**
         * InboxFileInfo
         * @description Information about a file in the inbox.
         */
        InboxFileInfo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /** Size Bytes */
            size_bytes: number;
            /** Modified */
            modified: string;
            /**
             * Type
             * @default file
             */
            type: string;
        };
        /**
         * InboxFileResult
         * @description Result for a single processed file.
         */
        InboxFileResult: {
            /** Source Path */
            source_path: string;
            /** Destination Path */
            destination_path?: string | null;
            /** Action */
            action: string;
            /** Classification */
            classification: string;
            /**
             * Added Tags
             * @default []
             */
            added_tags: string[];
            /** Error */
            error?: string | null;
        };
        /**
         * InboxFolderInfo
         * @description Information about a folder in the inbox.
         */
        InboxFolderInfo: {
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Type
             * @default folder
             */
            type: string;
            /**
             * Files
             * @default []
             */
            files: components["schemas"]["InboxFileInfo"][];
            /**
             * Folders
             * @default []
             */
            folders: components["schemas"]["InboxFolderInfo"][];
        };
        /**
         * InboxProcessRequest
         * @description Request body for inbox processing.
         */
        InboxProcessRequest: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
        };
        /**
         * InboxProcessResponse
         * @description Response for inbox processing.
         */
        InboxProcessResponse: {
            /** Processed */
            processed: number;
            /** Moved */
            moved: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Results */
            results: components["schemas"]["InboxFileResult"][];
        };
        /**
         * IndexRequest
         * @description Request for indexing.
         */
        IndexRequest: {
            /** Paths */
            paths?: string[] | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
        };
        /**
         * IndexResponse
         * @description Response for index operation.
         */
        IndexResponse: {
            /** Status */
            status: string;
            /** Job Id */
            job_id: string;
            /** Documents Queued */
            documents_queued: number;
        };
        /**
         * IndexStatusResponse
         * @description Response for index status.
         */
        IndexStatusResponse: {
            /** Status */
            status: string;
            /** Documents Indexed */
            documents_indexed: number;
            /** Documents Pending */
            documents_pending: number;
            /** Last Indexed At */
            last_indexed_at?: string | null;
            /** Current Job */
            current_job?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * MessageCreate
         * @description Request to add a message.
         */
        MessageCreate: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Sources */
            sources?: {
                [key: string]: unknown;
            }[] | null;
        };
        /**
         * PostgresStatsResponse
         * @description PostgreSQL database statistics.
         */
        PostgresStatsResponse: {
            /** File Count */
            file_count: number;
            /** Section Count */
            section_count: number;
            /** Tag Count */
            tag_count: number;
            /** Link Count */
            link_count: number;
            /** Chunk Count */
            chunk_count: number;
            /** Embedding Count */
            embedding_count: number;
            /** Last Sync */
            last_sync: string | null;
        };
        /**
         * ProviderInfo
         * @description Provider information.
         */
        ProviderInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Available */
            available: boolean;
            /** Base Url */
            base_url?: string | null;
            /**
             * Models
             * @default []
             */
            models: components["schemas"]["ProviderModel"][];
            /** Error */
            error?: string | null;
        };
        /**
         * ProviderModel
         * @description Model information within a provider.
         */
        ProviderModel: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Context Length
             * @default 128000
             */
            context_length: number;
            /**
             * Available
             * @default true
             */
            available: boolean;
        };
        /**
         * ProviderStatus
         * @description Provider status for health check.
         */
        ProviderStatus: {
            /** Available */
            available: boolean;
            /** Models Loaded */
            models_loaded?: string[] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * RAGTechniqueInfo
         * @description RAG technique information.
         */
        RAGTechniqueInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /**
         * SearchResponse
         * @description Search results response.
         */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
            /** Count */
            count: number;
        };
        /**
         * SearchResult
         * @description Single search result.
         */
        SearchResult: {
            /** File Path */
            file_path: string;
            /** Title */
            title: string;
            /** Heading */
            heading: string;
            /** Snippet */
            snippet: string;
            /** Rank */
            rank: number;
        };
        /**
         * SemanticSearchRequest
         * @description Request for semantic search.
         */
        SemanticSearchRequest: {
            /** Query */
            query: string;
            /**
             * Limit
             * @default 10
             */
            limit: number;
            /**
             * Rag Technique
             * @default basic
             */
            rag_technique: string;
        };
        /**
         * SemanticSearchResponse
         * @description Response for semantic search.
         */
        SemanticSearchResponse: {
            /** Results */
            results: components["schemas"]["SemanticSearchResult"][];
            /** Query Embedding Time Ms */
            query_embedding_time_ms?: number | null;
            /** Search Time Ms */
            search_time_ms?: number | null;
        };
        /**
         * SemanticSearchResult
         * @description A single semantic search result.
         */
        SemanticSearchResult: {
            /** Path */
            path: string;
            /** Title */
            title: string;
            /** Snippet */
            snippet: string;
            /** Score */
            score: number;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * SourceInfo
         * @description Source information for RAG response.
         */
        SourceInfo: {
            /** File Path */
            file_path: string;
            /** File Title */
            file_title: string;
            /** Section */
            section?: string | null;
            /** Similarity */
            similarity: number;
        };
        /**
         * StatsResponse
         * @description Database statistics response.
         */
        StatsResponse: {
            /** File Count */
            file_count: number;
            /** Section Count */
            section_count: number;
            /** Tag Count */
            tag_count: number;
            /** Link Count */
            link_count: number;
            /** Last Indexed */
            last_indexed: string | null;
        };
        /**
         * SyncRequest
         * @description Request for PostgreSQL sync.
         */
        SyncRequest: {
            /**
             * Mode
             * @default incremental
             */
            mode: string;
        };
        /**
         * SyncResponse
         * @description Response from PostgreSQL sync.
         */
        SyncResponse: {
            /** Files Added */
            files_added: number;
            /** Files Updated */
            files_updated: number;
            /** Files Deleted */
            files_deleted: number;
            /** Sections */
            sections: number;
            /** Tags */
            tags: number;
            /** Links */
            links: number;
            /** Chunks */
            chunks: number;
            /** Embeddings */
            embeddings: number;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VectorStoreStatus
         * @description Vector store status for health check.
         */
        VectorStoreStatus: {
            /** Type */
            type: string;
            /** Documents Indexed */
            documents_indexed: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_stats_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    get_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    semantic_search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemanticSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemanticSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_file_get: {
        parameters: {
            query: {
                /** @description Relative path to the file in the vault */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_backlinks_backlinks_get: {
        parameters: {
            query: {
                /** @description Relative path or filename to find backlinks for */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_reindex_reindex_post: {
        parameters: {
            query?: {
                /** @description Perform full rescan */
                full?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_index_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_index_status_index_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexStatusResponse"];
                };
            };
        };
    };
    ask_question_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_embedding_stats_embeddings_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbeddingStatsResponse"];
                };
            };
        };
    };
    process_inbox_inbox_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxProcessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inbox_files_inbox_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_inbox_contents_inbox_contents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxContentsResponse"];
                };
            };
        };
    };
    sync_to_postgres_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    postgres_stats_sync_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostgresStatsResponse"];
                };
            };
        };
    };
    sync_single_file_sync_file_post: {
        parameters: {
            query: {
                /** @description File path to sync */
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: {
                session_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_embeddings_embeddings_generate_post: {
        parameters: {
            query?: {
                /** @description Maximum chunks to process */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
